# Generated by Django 5.2 on 2025-10-14 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amit_logins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkStatusGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('S_NO', models.CharField(max_length=100)),
                ('DATE', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WORK_CODE', models.CharField(max_length=50)),
                ('WORK_DETAILS', models.TextField()),
                ('STARTING_DATE', models.DateField(blank=True, null=True)),
                ('ENDING_DATE', models.DateField(blank=True, null=True)),
                ('WORK_STATUS', models.CharField(choices=[('IN PROGRESS', 'IN PROGRESS'), ('COMPLETED', 'COMPLETED'), ('-', '-')], max_length=50)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='amit_logins.workstatusgroup')),
            ],
        ),
    ]
