# Generated by Django 5.2 on 2026-03-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amit_logins', '0003_chennaiinternshipregistration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChennaiPaymentVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_NO', models.IntegerField()),
                ('DATE', models.DateField()),
                ('VC_NO', models.CharField(max_length=100, unique=True)),
                ('PURPOSE', models.TextField()),
                ('ONLINE_PAYMENT', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Online (A/C)')),
                ('CASH_PAYMENT', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cash')),
            ],
            options={
                'verbose_name': 'Chennai Payment Voucher',
                'verbose_name_plural': 'Chennai Payment Vouchers',
            },
        ),
        migrations.CreateModel(
            name='NagercoilPaymentVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_NO', models.IntegerField()),
                ('DATE', models.DateField()),
                ('VC_NO', models.CharField(max_length=100, unique=True)),
                ('PURPOSE', models.TextField()),
                ('ONLINE_PAYMENT', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Online (A/C)')),
                ('CASH_PAYMENT', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cash')),
            ],
            options={
                'verbose_name': 'Nagercoil Payment Voucher',
                'verbose_name_plural': 'Nagercoil Payment Vouchers',
            },
        ),
        migrations.CreateModel(
            name='PudukottaiPaymentVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_NO', models.IntegerField()),
                ('DATE', models.DateField()),
                ('VC_NO', models.CharField(max_length=100, unique=True)),
                ('PURPOSE', models.TextField()),
                ('ONLINE_PAYMENT', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Online (A/C)')),
                ('CASH_PAYMENT', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cash')),
            ],
            options={
                'verbose_name': 'Pudukottai Payment Voucher',
                'verbose_name_plural': 'Pudukottai Payment Vouchers',
            },
        ),
        migrations.CreateModel(
            name='TirunelveliPaymentVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_NO', models.IntegerField()),
                ('DATE', models.DateField()),
                ('VC_NO', models.CharField(max_length=100, unique=True)),
                ('PURPOSE', models.TextField()),
                ('ONLINE_PAYMENT', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Online (A/C)')),
                ('CASH_PAYMENT', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cash')),
            ],
            options={
                'verbose_name': 'Tirunelveli Payment Voucher',
                'verbose_name_plural': 'Tirunelveli Payment Vouchers',
            },
        ),
    ]
