# Generated by Django 5.2 on 2026-03-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amit_logins', '0005_chennaiinternshipbill_chennaiproductbill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chennaiinternshipbill',
            name='PAYMENT_STATUS',
            field=models.CharField(choices=[('PARTIALLY PAID', 'PARTIALLY PAID'), ('25% PAID', '25% PAID'), ('50% PAID', '50% PAID'), ('75% PAID', '75% PAID'), ('FULLY PAID', 'FULLY PAID'), ('CANCELLED', 'CANCELLED')], default='IN PROGRESS', max_length=50),
        ),
        migrations.AlterField(
            model_name='chennaiproductbill',
            name='PAYMENT_STATUS',
            field=models.CharField(choices=[('PARTIALLY PAID', 'PARTIALLY PAID'), ('25% PAID', '25% PAID'), ('50% PAID', '50% PAID'), ('75% PAID', '75% PAID'), ('FULLY PAID', 'FULLY PAID'), ('CANCELLED', 'CANCELLED')], default='IN PROGRESS', max_length=50),
        ),
        migrations.AlterField(
            model_name='nagercoilinternshipbill',
            name='PAYMENT_STATUS',
            field=models.CharField(choices=[('PARTIALLY PAID', 'PARTIALLY PAID'), ('25% PAID', '25% PAID'), ('50% PAID', '50% PAID'), ('75% PAID', '75% PAID'), ('FULLY PAID', 'FULLY PAID'), ('CANCELLED', 'CANCELLED')], default='IN PROGRESS', max_length=50),
        ),
        migrations.AlterField(
            model_name='nagercoilproductbill',
            name='PAYMENT_STATUS',
            field=models.CharField(choices=[('PARTIALLY PAID', 'PARTIALLY PAID'), ('25% PAID', '25% PAID'), ('50% PAID', '50% PAID'), ('75% PAID', '75% PAID'), ('FULLY PAID', 'FULLY PAID'), ('CANCELLED', 'CANCELLED')], default='IN PROGRESS', max_length=50),
        ),
        migrations.AlterField(
            model_name='pudukottaiinternshipbill',
            name='PAYMENT_STATUS',
            field=models.CharField(choices=[('PARTIALLY PAID', 'PARTIALLY PAID'), ('25% PAID', '25% PAID'), ('50% PAID', '50% PAID'), ('75% PAID', '75% PAID'), ('FULLY PAID', 'FULLY PAID'), ('CANCELLED', 'CANCELLED')], default='IN PROGRESS', max_length=50),
        ),
        migrations.AlterField(
            model_name='pudukottaiproductbill',
            name='PAYMENT_STATUS',
            field=models.CharField(choices=[('PARTIALLY PAID', 'PARTIALLY PAID'), ('25% PAID', '25% PAID'), ('50% PAID', '50% PAID'), ('75% PAID', '75% PAID'), ('FULLY PAID', 'FULLY PAID'), ('CANCELLED', 'CANCELLED')], default='IN PROGRESS', max_length=50),
        ),
        migrations.AlterField(
            model_name='tirunelveliinternshipbill',
            name='PAYMENT_STATUS',
            field=models.CharField(choices=[('PARTIALLY PAID', 'PARTIALLY PAID'), ('25% PAID', '25% PAID'), ('50% PAID', '50% PAID'), ('75% PAID', '75% PAID'), ('FULLY PAID', 'FULLY PAID'), ('CANCELLED', 'CANCELLED')], default='IN PROGRESS', max_length=50),
        ),
        migrations.AlterField(
            model_name='tirunelveliproductbill',
            name='PAYMENT_STATUS',
            field=models.CharField(choices=[('PARTIALLY PAID', 'PARTIALLY PAID'), ('25% PAID', '25% PAID'), ('50% PAID', '50% PAID'), ('75% PAID', '75% PAID'), ('FULLY PAID', 'FULLY PAID'), ('CANCELLED', 'CANCELLED')], default='IN PROGRESS', max_length=50),
        ),
    ]
