# Generated by Django 5.2 on 2026-03-19 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amit_logins', '0006_alter_chennaiinternshipbill_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChennaiTaxInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('bill_to', models.TextField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gst_18', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount_with_gst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('round_off', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_in_words', models.TextField()),
            ],
            options={
                'verbose_name': 'Chennai Tax Invoice',
                'verbose_name_plural': 'Chennai Tax Invoices',
            },
        ),
        migrations.CreateModel(
            name='NagercoilTaxInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('bill_to', models.TextField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gst_18', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount_with_gst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('round_off', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_in_words', models.TextField()),
            ],
            options={
                'verbose_name': 'Nagercoil Tax Invoice',
                'verbose_name_plural': 'Nagercoil Tax Invoices',
            },
        ),
        migrations.CreateModel(
            name='PudukottaiTaxInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('bill_to', models.TextField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gst_18', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount_with_gst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('round_off', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_in_words', models.TextField()),
            ],
            options={
                'verbose_name': 'Pudukottai Tax Invoice',
                'verbose_name_plural': 'Pudukottai Tax Invoices',
            },
        ),
        migrations.CreateModel(
            name='TirunelveliTaxInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('bill_to', models.TextField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gst_18', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount_with_gst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('round_off', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_in_words', models.TextField()),
            ],
            options={
                'verbose_name': 'Tirunelveli Tax Invoice',
                'verbose_name_plural': 'Tirunelveli Tax Invoices',
            },
        ),
        migrations.CreateModel(
            name='ChennaiTaxInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField()),
                ('description', models.TextField()),
                ('qty', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='amit_logins.chennaitaxinvoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NagercoilTaxInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField()),
                ('description', models.TextField()),
                ('qty', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='amit_logins.nagercoiltaxinvoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PudukottaiTaxInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField()),
                ('description', models.TextField()),
                ('qty', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='amit_logins.pudukottaitaxinvoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TirunelveliTaxInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField()),
                ('description', models.TextField()),
                ('qty', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='amit_logins.tirunelvelitaxinvoice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
