# Generated by Django 5.2 on 2026-03-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amit_logins', '0009_remove_chennaiinternshipbill_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chennaitaxinvoice',
            name='BILL_TO',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nagercoiltaxinvoice',
            name='BILL_TO',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pudukottaitaxinvoice',
            name='BILL_TO',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tirunelvelitaxinvoice',
            name='BILL_TO',
            field=models.TextField(blank=True, null=True),
        ),
    ]
