# Generated by Django 5.2 on 2026-03-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amit_logins', '0010_alter_chennaitaxinvoice_bill_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chennaitaxinvoice',
            name='BILL_TO',
            field=models.TextField(default='AB TECHNOLOGIES\n14, First and Second Floor, Prajam Complex,\nS.T. Hindu College Road, Chettikulam, Nagercoil,\nKanyakumari District, Tamil Nadu, India - 629 002.\nContact: +919789224844\nGST : 33CKGPK5591Q1ZG'),
        ),
        migrations.AlterField(
            model_name='nagercoiltaxinvoice',
            name='BILL_TO',
            field=models.TextField(default='AB TECHNOLOGIES\n14, First and Second Floor, Prajam Complex,\nS.T. Hindu College Road, Chettikulam, Nagercoil,\nKanyakumari District, Tamil Nadu, India - 629 002.\nContact: +919789224844\nGST : 33CKGPK5591Q1ZG'),
        ),
        migrations.AlterField(
            model_name='pudukottaitaxinvoice',
            name='BILL_TO',
            field=models.TextField(default='AB TECHNOLOGIES\n14, First and Second Floor, Prajam Complex,\nS.T. Hindu College Road, Chettikulam, Nagercoil,\nKanyakumari District, Tamil Nadu, India - 629 002.\nContact: +919789224844\nGST : 33CKGPK5591Q1ZG'),
        ),
        migrations.AlterField(
            model_name='tirunelvelitaxinvoice',
            name='BILL_TO',
            field=models.TextField(default='AB TECHNOLOGIES\n14, First and Second Floor, Prajam Complex,\nS.T. Hindu College Road, Chettikulam, Nagercoil,\nKanyakumari District, Tamil Nadu, India - 629 002.\nContact: +919789224844\nGST : 33CKGPK5591Q1ZG'),
        ),
    ]
