# Generated by Django 5.2 on 2026-04-20 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amit_logins', '0011_alter_chennaitaxinvoice_bill_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMITNagercoilComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COMPONENT_CODE', models.CharField(max_length=50, unique=True)),
                ('COMPONENT_NAME', models.CharField(max_length=255)),
                ('RANGE', models.CharField(max_length=100)),
                ('CATEGORY', models.CharField(default='OTHERS', max_length=100)),
                ('AVAILABLE_QUANTITY', models.IntegerField(default=0)),
                ('TOTAL_STOCK', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'AMIT Nagercoil Component',
                'verbose_name_plural': 'AMIT Nagercoil Components',
            },
        ),
        migrations.CreateModel(
            name='ComponentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=100, unique=True)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='chennaitaxinvoice',
            name='INVOICE_NO',
            field=models.CharField(default='AMIT/26-27/', max_length=100),
        ),
        migrations.AlterField(
            model_name='nagercoiltaxinvoice',
            name='INVOICE_NO',
            field=models.CharField(default='AMIT/26-27/', max_length=100),
        ),
        migrations.AlterField(
            model_name='pudukottaitaxinvoice',
            name='INVOICE_NO',
            field=models.CharField(default='AMIT/26-27/', max_length=100),
        ),
        migrations.AlterField(
            model_name='tirunelvelitaxinvoice',
            name='INVOICE_NO',
            field=models.CharField(default='AMIT/26-27/', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('HARDWARE PROJECT DEVELOPMENT TEAM', 'HARDWARE PROJECT DEVELOPMENT TEAM'), ('ADMIN TEAM', 'ADMIN TEAM'), ('ADMIN-MANAGEMENT WORK TEAM', 'ADMIN-MANAGEMENT WORK TEAM'), ('STOCK MANAGEMENT TEAM', 'STOCK MANAGEMENT TEAM')], max_length=50),
        ),
        migrations.CreateModel(
            name='ComponentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_code', models.CharField(max_length=50)),
                ('component_name', models.CharField(max_length=255)),
                ('component_range', models.CharField(default='', max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('ADDED', 'ADDED'), ('TAKEN', 'TAKEN')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('availability', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Component Transaction',
                'verbose_name_plural': 'Component Transactions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
