# Generated by Django 5.2 on 2026-04-22 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amit_logins', '0012_amitnagercoilcomponent_componentcategory_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AMITNagercoilComponent',
            new_name='NagercoilComponent',
        ),
        migrations.AlterModelOptions(
            name='nagercoilcomponent',
            options={'verbose_name': 'Nagercoil Component', 'verbose_name_plural': 'Nagercoil Components'},
        ),
    ]
